[package]
name = "mos"
version = "0.1.0"
authors = ["halloween-jack <halloween.jack.dev@gmail.com>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
